<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ZofriDescriptores;

class DescriptoresSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'codigo' => '1',
                'nombre' => 'Nombre Del Producto',
                'descripcion' => 'Nombre de la Mercancía           ',
                'etiqueta_impresion' => 'Nombre',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => 'D',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '2',
                'nombre' => 'Modelo',
                'descripcion' => 'Modelo de la Mercancía',
                'etiqueta_impresion' => 'Modelo',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => 'D',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '3',
                'nombre' => 'Tipo',
                'descripcion' => 'Tipo',
                'etiqueta_impresion' => 'Tipo',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => 'D',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '4',
                'nombre' => 'Marca del Producto',
                'descripcion' => 'Marca del Producto',
                'etiqueta_impresion' => 'Marca',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => 'D',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '5',
                'nombre' => 'Año',
                'descripcion' => 'Año',
                'etiqueta_impresion' => 'Año',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '4',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '6',
                'nombre' => 'Tipo de Encendido',
                'descripcion' => 'Tipo de Encendido',
                'etiqueta_impresion' => 'Encend',
                'tipo_de_dato_codigo' => 'LISTA',
                'lista_de_valor_codigo' => '05',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '7',
                'nombre' => 'Número de Serie',
                'descripcion' => 'Número de Serie',
                'etiqueta_impresion' => 'N° Serie',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '8',
                'nombre' => 'Número de Chassis',
                'descripcion' => 'Número de Chassis',
                'etiqueta_impresion' => 'Chassis',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '9',
                'nombre' => 'Número de Motor',
                'descripcion' => 'Número de Motor',
                'etiqueta_impresion' => 'Motor',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '10',
                'nombre' => 'Cilindrada',
                'descripcion' => 'Cilindrada',
                'etiqueta_impresion' => 'Cilind',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '5',
                'decimales' => '2',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '11',
                'nombre' => 'Peso Total con Carga Máxima',
                'descripcion' => 'Peso Total con Carga Máxima',
                'etiqueta_impresion' => 'Peso.Tot.Carg.Max.',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '6',
                'decimales' => '2',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '12',
                'nombre' => 'Asientos',
                'descripcion' => 'Asientos',
                'etiqueta_impresion' => 'Asientos',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '3',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '13',
                'nombre' => 'Tipo Cabina',
                'descripcion' => 'Tipo Cabina',
                'etiqueta_impresion' => 'Cabina',
                'tipo_de_dato_codigo' => 'LISTA',
                'lista_de_valor_codigo' => '02',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '14',
                'nombre' => 'Capacidad Carga Util en Kgrs.',
                'descripcion' => 'Capacidad Carga Util en Kgrs.',
                'etiqueta_impresion' => 'Cap.Carg.Util.Kg.',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '6',
                'decimales' => '2',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '15',
                'nombre' => 'Capacidad Carga Util en Tonel. Mts.',
                'descripcion' => 'Capacidad Carga Util en Tonel. Mts.',
                'etiqueta_impresion' => 'Cap.Carg.Util.Ton.',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '6',
                'decimales' => '2',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '16',
                'nombre' => 'Sistema de Tracción',
                'descripcion' => 'Sistema de Tracción',
                'etiqueta_impresion' => 'Tracción',
                'tipo_de_dato_codigo' => 'LISTA',
                'lista_de_valor_codigo' => '06',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '17',
                'nombre' => 'Descripción',
                'descripcion' => 'Descripción',
                'etiqueta_impresion' => 'Descrip',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '18',
                'nombre' => 'Tipo de Vehículo',
                'descripcion' => 'Tipo de Vehículo',
                'etiqueta_impresion' => 'T.Vehic',
                'tipo_de_dato_codigo' => 'LISTA',
                'lista_de_valor_codigo' => '01',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '19',
                'nombre' => 'Color Unico',
                'descripcion' => 'Color Unico',
                'etiqueta_impresion' => 'Color',
                'tipo_de_dato_codigo' => 'LISTA',
                'lista_de_valor_codigo' => '03',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '20',
                'nombre' => 'Color 1',
                'descripcion' => 'Color 1',
                'etiqueta_impresion' => 'Color',
                'tipo_de_dato_codigo' => 'LISTA',
                'lista_de_valor_codigo' => '03',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '21',
                'nombre' => 'Color 2',
                'descripcion' => 'Color 2',
                'etiqueta_impresion' => 'Color',
                'tipo_de_dato_codigo' => 'LISTA',
                'lista_de_valor_codigo' => '03',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '22',
                'nombre' => 'Color 3',
                'descripcion' => 'Color 3',
                'etiqueta_impresion' => 'Color',
                'tipo_de_dato_codigo' => 'LISTA',
                'lista_de_valor_codigo' => '03',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '23',
                'nombre' => 'Código Producto',
                'descripcion' => 'Código Producto',
                'etiqueta_impresion' => 'Cod.Prod',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '24',
                'nombre' => 'Información Adicional',
                'descripcion' => 'Información Adicional',
                'etiqueta_impresion' => 'Inf.Adic.',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => 'G',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '25',
                'nombre' => 'Nombre comercial',
                'descripcion' => 'Nombre comercial',
                'etiqueta_impresion' => 'Nomb.Come',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '26',
                'nombre' => 'Composición (%)',
                'descripcion' => 'Composición (%)',
                'etiqueta_impresion' => 'Comp%',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '3',
                'decimales' => '2',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '27',
                'nombre' => 'Material Capellada',
                'descripcion' => 'Material Capellada',
                'etiqueta_impresion' => 'Mat.Capellada',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '28',
                'nombre' => 'Material Planta',
                'descripcion' => 'Material Planta',
                'etiqueta_impresion' => 'Mat.Planta',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '29',
                'nombre' => 'Peso',
                'descripcion' => 'Peso',
                'etiqueta_impresion' => 'Peso',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '6',
                'decimales' => '2',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '30',
                'nombre' => 'Talla',
                'descripcion' => 'Talla',
                'etiqueta_impresion' => 'Talla',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '5',
                'decimales' => '2',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '31',
                'nombre' => 'Presentación',
                'descripcion' => 'Presentación',
                'etiqueta_impresion' => 'Presentación',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '32',
                'nombre' => 'Tipo envase',
                'descripcion' => 'Tipo envase',
                'etiqueta_impresion' => 'T.Env',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '33',
                'nombre' => 'Tipo de producto',
                'descripcion' => 'Tipo de producto',
                'etiqueta_impresion' => 'T.Prod',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '34',
                'nombre' => 'Fabricante',
                'descripcion' => 'Fabricante',
                'etiqueta_impresion' => 'Fab',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '35',
                'nombre' => 'Año Fabricación',
                'descripcion' => 'Año Fabricación',
                'etiqueta_impresion' => 'Año',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '4',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '36',
                'nombre' => 'Variedad',
                'descripcion' => 'Variedad',
                'etiqueta_impresion' => 'Var',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '37',
                'nombre' => 'Capacidad de Envase (Kg)',
                'descripcion' => 'Capacidad de Envase (Kg)',
                'etiqueta_impresion' => 'Cap.Env.KG',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '6',
                'decimales' => '2',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '38',
                'nombre' => 'Capacidad (Mb)',
                'descripcion' => 'Capacidad (Mb)',
                'etiqueta_impresion' => 'Cap.MB',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '6',
                'decimales' => '2',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '39',
                'nombre' => 'Capacidad de Envase (gr)',
                'descripcion' => 'Capacidad de Envase (gr)',
                'etiqueta_impresion' => 'Cap.Env.GR',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '6',
                'decimales' => '2',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '40',
                'nombre' => 'Capacidad de Envase (cl)',
                'descripcion' => 'Capacidad de Envase (cl)',
                'etiqueta_impresion' => 'Cap.Env.CL',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '6',
                'decimales' => '2',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '41',
                'nombre' => 'Capacidad de Envase (cc)',
                'descripcion' => 'Capacidad de Envase (cc)',
                'etiqueta_impresion' => 'Cap.Env.CC',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '6',
                'decimales' => '2',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '42',
                'nombre' => 'Capacidad de Envase (ml)',
                'descripcion' => 'Capacidad de Envase (ml)',
                'etiqueta_impresion' => 'Cap.Env.ML',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '6',
                'decimales' => '2',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '43',
                'nombre' => 'Capacidad de Envase (N° de Unidades)',
                'descripcion' => 'Capacidad de Envase (N° de Unidades)',
                'etiqueta_impresion' => 'Cap.Env.UN',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '6',
                'decimales' => '2',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '44',
                'nombre' => 'Capacidad de Envase (N° de Cigarrillos)',
                'descripcion' => 'Capacidad de Envase (N° de Cigarrillos)',
                'etiqueta_impresion' => 'Cap.Env.CIG',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '6',
                'decimales' => '2',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '45',
                'nombre' => 'Tipo de Software',
                'descripcion' => 'Tipo de Software',
                'etiqueta_impresion' => 'T.Soft',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '46',
                'nombre' => 'Nombre de Software',
                'descripcion' => 'Nombre de Software',
                'etiqueta_impresion' => 'Software',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '47',
                'nombre' => 'Marca de Software',
                'descripcion' => 'Marca de Software',
                'etiqueta_impresion' => 'Marca.Soft',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '48',
                'nombre' => 'Numeración (Francesa)',
                'descripcion' => 'Numeración (Francesa)',
                'etiqueta_impresion' => 'Num.Francesa',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '49',
                'nombre' => 'Marca del Vehículo',
                'descripcion' => 'Marca del Vehículo',
                'etiqueta_impresion' => 'Marca.Vhc',
                'tipo_de_dato_codigo' => 'LISTA',
                'lista_de_valor_codigo' => '04',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '50',
                'nombre' => 'Tipo de Combustible',
                'descripcion' => 'Tipo de Combustible',
                'etiqueta_impresion' => 'Combustible',
                'tipo_de_dato_codigo' => 'LISTA',
                'lista_de_valor_codigo' => '07',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '51',
                'nombre' => 'Vehículo de destino',
                'descripcion' => 'Vehículo de destino',
                'etiqueta_impresion' => 'Vehi.Destino',
                'tipo_de_dato_codigo' => 'LISTA',
                'lista_de_valor_codigo' => '01',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '52',
                'nombre' => 'Carga Máxima Kgs.',
                'descripcion' => 'Carga Máxima en Kgs.',
                'etiqueta_impresion' => 'Carg.Max.Kgs',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '6',
                'decimales' => '2',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '53',
                'nombre' => 'Carga Máxima Ton.',
                'descripcion' => 'Carga Máxima en Toneladas',
                'etiqueta_impresion' => 'Carg.Max.Ton',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '6',
                'decimales' => '2',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '54',
                'nombre' => 'Colores',
                'descripcion' => 'Colores',
                'etiqueta_impresion' => 'Colores',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '55',
                'nombre' => 'Peso Total Kgs.',
                'descripcion' => 'Peso Total en Kgs.',
                'etiqueta_impresion' => 'Peso.Tot.Kgs',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '6',
                'decimales' => '2',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '56',
                'nombre' => 'Peso Total Ton.',
                'descripcion' => 'Peso Total en Toneladas',
                'etiqueta_impresion' => 'Peso.Tot.Ton',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '6',
                'decimales' => '2',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '57',
                'nombre' => 'Puertas',
                'descripcion' => 'Cantidad Puertas',
                'etiqueta_impresion' => 'Puertas',
                'tipo_de_dato_codigo' => 'NUME',
                'lista_de_valor_codigo' => '',
                'enteros' => '2',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'S', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '58',
                'nombre' => 'Tracción Migrada',
                'descripcion' => 'Sistema de Tracción Migrada desde SVR',
                'etiqueta_impresion' => 'Tracción',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'N', // S: Vigente, N: No vigente
            ],
            [
                'codigo' => '59',
                'nombre' => 'Tipo de Item Migrado',
                'descripcion' => 'Tipo de Item Migrado desde SVR',
                'etiqueta_impresion' => 'T.Item',
                'tipo_de_dato_codigo' => 'ALFANUM',
                'lista_de_valor_codigo' => '',
                'enteros' => '0',
                'decimales' => '0',
                'obligatoriedad' => '',
                'vigencia' => 'N', // S: Vigente, N: No vigente
            ],
        ];

        foreach ($data as $item) {
            ZofriDescriptores::create($item);
        }
    }
}
